substitutions:
  _REGION: asia-northeast1
  _AR_REPO_SERVICE: myp-release-top-app
  _AR_REPO_COMMON: myp-release-common-base
  _SERVICE: top-app

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=RUNTIME_BASE_IMAGE=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_COMMON}/base-runtime-jre21:latest'
      - '--build-arg=BUILD_BASE_IMAGE=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_COMMON}/base-build-maven21:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_SERVICE}/${_SERVICE}:$BUILD_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_SERVICE}/${_SERVICE}:$BUILD_ID'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_SERVICE}/${_SERVICE}:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--ingress=internal-and-cloud-load-balancing'
      - '--allow-unauthenticated'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_SERVICE}/${_SERVICE}:$BUILD_ID'
